builds:
  - env:
    - CGO_ENABLED=0
    main: main.go
    binary: bin/{{ .ProjectName }}
    goos:
      - linux
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    ignore:
      - goos: freebsd
        goarch: arm

checksum:
  # You can change the name of the checksums file.
  # Default is `{{ .ProjectName }}_{{ .Version }}_checksums.txt`.
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
- format: tar.gz
  files:
    - LICENSE
    - README.md
    - CHANGELOG.md

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  #name_template: "{{.ProjectName}}-v{{.Version}}"
